name: flemozi
description: A powerful emoji picker
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  fuzzywuzzy: ^0.2.0
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.1.3
  http: ^0.13.5
  riverpod: ^2.1.3
  window_manager: ^0.3.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  hotkey_manager:
    git:
      url: https://github.com/leanflutter/hotkey_manager.git
      ref: 604523dd6edfb54e643f577512ea698c8debb96d
  launch_at_startup: ^0.2.2
  package_info_plus: ^3.0.3
  shared_preferences: ^2.0.17
  alfred: ^1.0.0+1
  system_theme: ^2.1.0
  flutter_svg: ^2.0.2
  url_launcher: ^6.1.10
  fl_query: ^1.0.0-alpha.2
  fl_query_hooks: ^1.0.0-alpha.2
  giphy_api_client: ^0.1.3
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.0
  visibility_detector: ^0.4.0+2
  pasteboard: ^0.2.0
  flutter_cache_manager: ^3.3.0
  super_clipboard: ^0.2.3+1
  path: ^1.8.2
  easy_debounce: ^2.0.3
  uuid: ^3.0.7
  shimmer: ^2.0.0
  hive_flutter: ^1.1.0
  auto_size_text: ^3.0.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  melos: ^3.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.12.0"
  html: ^0.15.2
  pub_api_client: ^2.4.0

flutter:
  uses-material-design: true    
  assets:
    - assets/
    - assets/twemoji/
    - .env

flutter_icons:
  android: false
  ios: false
  image_path: "assets/logo.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true